import { IMAGES } from './constants';

export const BOAT_MODELS = {

  // ── RECREATIONAL ──
  recreational: {
    category: 'Lifestyle Series',
    models: [
      {
        id: 'mt-21',
        name: 'MT-21',
        tagline: 'Compact Luxury & Performance',
        price: 'From $85,000',
        coverImage: IMAGES.mt21,
        images: [
          IMAGES.mt21Gallery1,
          IMAGES.mt21Gallery2,
          IMAGES.mt21Gallery3,
          IMAGES.mt21Gallery4,
          IMAGES.mt21Gallery5,
        ],
        pdfEs: '/docs/ficha-mt21-es.pdf',
        pdfEn: '/docs/ficha-mt21-en.pdf',
        specs: {
          loa:          { en: '21 ft', es: '6.40 m' },
          beam:         { en: '8.5 ft', es: '2.33 m' },
          depth:        { en: '1.33 m', es: '1.33 m' },
          draft:        { en: '0.59 m', es: '0.59 m' },
          passengers:   { en: '11 pax', es: '11 pax' },
          fuelCapacity: { en: '60 GAL', es: '60 GAL' },
          maxLoad:      { en: '1400 kg', es: '1400 kg' },
          engines:      { en: '250 HP', es: '250 HP' },
        },
        features: {
          en: [
            'Command, control and monitoring system',
            'Steering compass / Manual binoculars',
            'Navigation lights / Marine spotlight',
            'GPS / Marine VHF radio / Marine UHF radio',
            'Speaker system / Electric horn',
            'Aluminum oars / Toolbox / Telescopic boat hook',
            'Three 12V batteries / Battery switch',
            'Two 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-pound ABC type fire extinguishers',
            '3" type D fender / Four 8" fenders',
            'SIX 10" cleats / Nylon rope',
            'Stainless steel swivel shackles',
            '22-pound aluminum anchor / Stainless steel chain',
            '26 life jackets / Two life rings',
            'Outboard motor guard / Bow Guard (Push kneel)',
          ],
          es: [
            'Sistema de comando, control y vigilancia',
            'Compás magnético / Binoculares marinos',
            'Luces de navegación / Reflector fijo',
            'GPS / Radio VHF marino / Radio UHF',
            'Altavoz con altoparlante / Pito eléctrico',
            'Remos en aluminio / Caja de herramientas / Bichero telescópico',
            'Tres baterías 12V / Switch de baterías',
            'Dos bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8"',
            'Seis cornamusas de trabajo de 10"',
            'Cable de nylon / Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '26 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
      {
        id: 'mt-31',
        name: 'MT-31',
        tagline: 'The Ultimate Day Cruiser',
        price: 'From $165,000',
        coverImage: IMAGES.mt31,
        images: [
          IMAGES.mt31Gallery1,
          IMAGES.mt31Gallery2,
          IMAGES.mt31Gallery3,
          IMAGES.mt31Gallery4,
          IMAGES.mt31Gallery5,
        ],
        pdfEs: '/docs/ficha-mt31-es.pdf',
        pdfEn: '/docs/ficha-mt31-en.pdf',
        specs: {
          loa:          { en: '31 ft', es: '9.50 m' },
          beam:         { en: '9.5 ft', es: '2.90 m' },
          depth:        { en: '1.60 m', es: '1.60 m' },
          draft:        { en: '0.59 m', es: '0.59 m' },
          passengers:   { en: '13 pax', es: '13 pax' },
          fuelCapacity: { en: '120 GAL', es: '120 GAL' },
          maxLoad:      { en: '3630 kg', es: '3630 kg' },
          engines:      { en: '2 x 250 HP', es: '2 x 250 HP' },
        },
        features: {
          en: [
            'Command, control and monitoring system',
            'Steering compass / Manual binoculars',
            'Navigation lights / Marine spotlight',
            'GPS / Marine VHF radio / Marine UHF radio',
            'Speaker system / Electric horn',
            'Aluminum oars / Toolbox / Telescopic boat hook',
            'Three 12V batteries / Battery switch / Electric cables',
            'Two 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-pound ABC type fire extinguishers',
            '3" type D fender / Four 8" fenders',
            'SIX 10" cleats / Nylon rope',
            'Stainless steel swivel shackles',
            '22-pound aluminum anchor / Stainless steel chain',
            '26 life jackets / Two life rings',
            'Outboard motor guard / Bow Guard (Push kneel)',
          ],
          es: [
            'Sistema de comando, control y vigilancia',
            'Compás magnético / Binoculares marinos',
            'Luces de navegación / Reflector fijo',
            'GPS / Radio VHF marino / Radio UHF',
            'Altavoz con altoparlante / Pito eléctrico',
            'Remos en aluminio / Caja de herramientas / Bichero telescópico',
            'Tres baterías 12V / Switch de baterías / Cables eléctricos',
            'Dos bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8"',
            'Seis cornamusas de trabajo de 10"',
            'Cable de nylon / Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '26 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
       {
        id: 'gaira-24',
        name: 'Gaira 24',
        tagline: 'Compact Professional Vessel',
        price: 'Custom Quote',
        coverImage: IMAGES.gaira24Profile,
        images: [
          IMAGES.gaira24Gallery1,
          IMAGES.gaira24Gallery2,
          IMAGES.gaira24Gallery3,
          IMAGES.gaira24Gallery4,
          IMAGES.gaira24Gallery5,
        ],
        pdfEs: '/docs/ficha-gaira24-es.pdf',
        pdfEn: '/docs/ficha-gaira24-en.pdf',
        specs: {
          loa:      { en: '38 ft', es: '11.60 m' },
          beam:     { en: '12 ft', es: '3.70 m' },
          crew:     { en: '3-4 crew', es: '3-4 tripulantes' },
          engines:  { en: 'Twin Diesel 500-700 HP', es: 'Doble Diésel 500-700 HP' },
          maxSpeed: { en: '30 knots', es: '30 nudos' },
          range:    { en: '250 nm', es: '250 mn' },
        },
        features: {
          en: [
            'Commercial grade hull',
            'Professional navigation equipment',
            'Ergonomic crew area',
            'VHF and communication systems',
            'Weather protection',
            'Easy boarding systems',
            'Shock-mitigating crew seats',
            'Advanced radar system',
            'Fuel-efficient diesel engines',
            'Reinforced structural frame',
          ],
          es: [
            'Casco de grado comercial',
            'Equipos de navegación profesional',
            'Área de tripulación ergonómica',
            'Sistemas VHF y comunicaciones',
            'Protección climática',
            'Sistemas de embarque fácil',
            'Asientos de tripulación anti-impacto',
            'Sistema avanzado de radar',
            'Motores diésel de bajo consumo',
            'Estructura reforzada',
          ],
        },
      },
      {
        id: 'hunter43',
        name: 'Hunter 43',
        tagline: 'Luxury & Performance',
        price: '0n Request',
        coverImage: IMAGES.hunter43,
        images: [
          IMAGES.hunter43Gallery1     ,
          IMAGES.hunter43Gallery2,
          IMAGES.hunter43Gallery3,
          IMAGES.hunter43Gallery4,
          IMAGES.hunter43Gallery5,

        ],

        pdfEs: '/docs/ficha-hunter43-es.pdf',
        pdfEn: '/docs/ficha-hunter43-en.pdf',
        specs: {
      loa:          { en: '21 ft', es: '6.40 m' },
          beam:         { en: '8.5 ft', es: '2.33 m' },
          depth:        { en: '1.33 m', es: '1.33 m' },
          draft:        { en: '0.59 m', es: '0.59 m' },
          passengers:   { en: '11 pax', es: '11 pax' },
          fuelCapacity: { en: '60 GAL', es: '60 GAL' },
          maxLoad:      { en: '1400 kg', es: '1400 kg' },
          engines:      { en: '250 HP', es: '250 HP' },
        },
        features: {
          en: [
            'Command, control and monitoring system',
            'Steering compass / Manual binoculars',
            'Navigation lights / Marine spotlight',
            'GPS / Marine VHF radio / Marine UHF radio',
            'Speaker system / Electric horn',
            'Aluminum oars / Toolbox / Telescopic boat hook',
            'Three 12V batteries / Battery switch / Electric cables',
            'Two 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-pound ABC type fire extinguishers',
            '3" type D fender / Four 8" fenders',
            'SIX 10" cleats / Nylon rope',
            'Stainless steel swivel shackles',
            '22-pound aluminum anchor / Stainless steel chain',
            '26 life jackets / Two life rings',
            'Outboard motor guard / Bow Guard (Push kneel)',
          ],
          es: [
             'Sistema de comando, control y vigilancia',
            'Compás magnético / Binoculares marinos',
            'Luces de navegación / Reflector fijo',
            'GPS / Radio VHF marino / Radio UHF',
            'Altavoz con altoparlante / Pito eléctrico',
            'Remos en aluminio / Caja de herramientas / Bichero telescópico',
            'Tres baterías 12V / Switch de baterías / Cables eléctricos',
            'Dos bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8"',
            'Seis cornamusas de trabajo de 10"',
            'Cable de nylon / Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '26 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
    ],
  },

  // ── INSTITUTIONAL ──
  institutional: {
    category: 'Professional Series',
    models: [
      {
        id: 'pilot-42',
        name: 'Pilot 42',
        tagline: 'Professional Harbor Pilot Vessel',
        price: 'Custom Quote',
        coverImage: IMAGES.pilot42,
        images: [
          IMAGES.pilot42Gallery1,
          IMAGES.pilot42Gallery2,
          IMAGES.pilot42Gallery3,
          IMAGES.pilot42Gallery4,
          IMAGES.pilot42Gallery5,
        ],
        pdfEs: '/docs/ficha-pilot42-es.pdf',
        pdfEn: '/docs/ficha-pilot42-en.pdf',
        specs: {
          loa:          { en: '12.8 m', es: '12.8 m' },
          beam:         { en: '3.15 m', es: '3.15 m' },
          depth:        { en: '1.65 m', es: '1.65 m' },
          draft:        { en: '0.55 m', es: '0.55 m' },
          passengers:   { en: '2 Crew / 5 pax', es: '2 tripulantes / 5 pax' },
          waterTank:    { en: '50 GAL', es: '50 GAL' },
          fuelCapacity: { en: '20 GAL Diesel / 275 GAL Gasoline', es: '20 GAL ACPM / 275 GAL Gasolina' },
          maxLoad:      { en: '3900 kg', es: '3900 kg' },
          engines:      { en: '2 x 350 HP Mercury', es: '2 x 350 HP Mercury' },
        },
        features: {
          en: [
            'Magnetic compass / GPS / Marine VHF radio',
            'Navigation lights (green/red) / Strobe light / Search lights / Cabin lights',
            '02 12V engine batteries / 02 12V service batteries',
            '03 Orion TR converters / AC-DC electrical control panel',
            '7KW generator (optional)',
            'Ergonomic suspension seats (optional)',
            '16,000 BTU air conditioner (optional)',
            'Electric stove (optional) / 90L minibar (optional)',
            'Cabin berth / Bathroom',
            'Three 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-lb ABC fire extinguishers',
            '3" D-type fender / Four 8" fenders',
            'Six 10" working cleats / Nylon rope',
            'Stainless steel shackle',
            '22-lb aluminum anchor / Stainless steel chain',
            '07 life jackets / 02 lifebuoys',
            'Outboard engine guards / Keel protector (push kneel)',
          ],
          es: [
            'Compás magnético / GPS / Radio VHF marino',
            'Luces de navegación verde-roja / Luz estroboscópica / Luz exploradora / Luces de cabina',
            '02 baterías para motores 12V / 02 baterías de servicio 12V',
            '03 Convertidores Orión TR / Caja de mando eléctrica ACDC',
            'Planta generadora 7KW (opcional)',
            'Sillas ergonómicas con suspensión (opcional)',
            'Aire acondicionado 16,000 BTU (opcional)',
            'Estufa eléctrica (opcional) / Mini bar 90L (opcional)',
            'Camarote / Baño',
            'Tres bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8"',
            'Seis cornamusas de trabajo de 10" / Cabo de nylon',
            'Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '07 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
     
    ],
  },

  // ── MILITARY ──
  military: {
    category: 'Defense & Tactical Series',
    models: [
      {
        id: 'alligator-37',
        name: 'Alligator 37',
        tagline: 'Military Grade Tactical Patrol',
        price: 'Government Contract',
        coverImage: IMAGES.alligator37,
        images: [
          IMAGES.alligator37Gallery1,
          IMAGES.alligator37Gallery2,
          IMAGES.alligator37Gallery3,
          IMAGES.alligator37Gallery4,
          IMAGES.alligator37Gallery5,
        ],
        pdfEs: '/docs/ficha-alligator37-es.pdf',
        pdfEn: '/docs/ficha-alligator37-en.pdf',
        specs: {
          loa:          { en: '11.27 m', es: '11.27 m' },
          beam:         { en: '2.9 m', es: '2.9 m' },
          depth:        { en: '1.7 m', es: '1.7 m' },
          draft:        { en: '0.6 m', es: '0.6 m' },
          passengers:   { en: '4 Crew / 28 pax', es: '4 tripulantes / 28 pax' },
          fuelCapacity: { en: '360 GAL', es: '360 GAL' },
          maxLoad:      { en: '4800 kg', es: '4800 kg' },
        },
        features: {
          en: [
            'Command, control and monitoring system',
            'Steering compass / Manual binoculars',
            'Navigation lights / Marine spotlight',
            'GPS / Marine VHF radio / Marine UHF radio',
            'Speaker system / Electric horn',
            'Aluminum oars / Toolbox / Telescopic boat hook',
            'Three 12V batteries / Battery switch / Electrical cables',
            'Two 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-pound ABC type fire extinguishers',
            '3" type D fender / Four 8" fenders / Aluminum trailer',
            'SIX 10" cleats / Nylon rope / Stainless steel swivel shackles',
            '22-pound aluminum anchor / Stainless steel chain',
            '2x 14" stainless steel ammo stands / 2x M-60 machine gun mounts',
            '32 life jackets / Two life rings',
            'Outboard motor guard / Bow Guard (Push kneel)',
          ],
          es: [
            'Sistema de comando, control y vigilancia',
            'Compás magnético / Binoculares marinos',
            'Luces de navegación / Reflector fijo',
            'GPS / Radio VHF marino / Radio UHF',
            'Altavoz con altoparlante / Pito eléctrico',
            'Remos en aluminio / Caja de herramientas / Bichero telescópico',
            'Tres baterías 12V / Switch de baterías / Cables eléctricos',
            'Tres bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8" / Trailer de aluminio',
            'Seis cornamusas de trabajo de 10" / Cabo de nylon / Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '02 cajas acero inox 14" para munición / 02 bases para ametralladora M-60',
            '32 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
     
    ],
  },
};

export const STORE_PRODUCTS = [
  { id: 1, name: 'Maritima Premium Polo',  category: 'Apparel',            price: 65,  image: IMAGES.storeApparel },
  { id: 2, name: 'Marine Safety Kit',       category: 'Gear & Accessories', price: 149, image: IMAGES.storeGear },
  { id: 3, name: 'GPS Chartplotter Pro',    category: 'Electronics',        price: 899, image: IMAGES.storeElectronics },
  { id: 4, name: 'Maritima Cap',            category: 'Apparel',            price: 35,  image: IMAGES.storeApparel },
  { id: 5, name: 'Boat Fender Set',         category: 'Gear & Accessories', price: 89,  image: IMAGES.storeGear },
  { id: 6, name: 'Marine Radio VHF',        category: 'Electronics',        price: 349, image: IMAGES.storeElectronics },
];

export const NEWS_ARTICLES = [
  {
    id: 1,
    title: 'Maritima Boats Launches New MT-31 Model',
    excerpt: 'Our latest addition to the Lifestyle Series brings unprecedented luxury and performance to the recreational boating market.',
    date: '2026-02-15',
    category: 'Product Launch',
    image: IMAGES.mt31,
  },
  {
    id: 2,
    title: 'Magdalena Yacht Wins Prestigious Design Award',
    excerpt: 'The Magdalena, our custom-built superyacht, has been honored with the International Yacht Design Award for its innovative design and craftsmanship.',
    date: '2026-01-20',
    category: 'Awards',
    image: IMAGES.magdalena,
  },
  {
    id: 3,
    title: 'Defense Contract: Alligator Series Expansion',
    excerpt: 'Maritima Boats secures major contract to deliver tactical vessels to international defense forces.',
    date: '2025-12-10',
    category: 'Business',
    image: IMAGES.alligator37,
  },
];
