import { IMAGES } from './constants';

export const BOAT_MODELS = {

  // ── RECREATIONAL ──
  recreational: {
    category: 'Lifestyle Series',
    models: [
      {
        id: 'mt-21',
        name: 'MT-21',
        tagline: 'Compact Luxury & Performance',
        price: 'From $85,000',
        coverImage: IMAGES.mt21,
        images: [
          IMAGES.mt21Gallery1,
          IMAGES.mt21Gallery2,
          IMAGES.mt21Gallery3,
          IMAGES.mt21Gallery4,
          IMAGES.mt21Gallery5,
        ],
        pdfEs: '/docs/ficha-mt21-es.pdf',
        pdfEn: '/docs/ficha-mt21-en.pdf',
        specs: {
          loa:          { en: '21 ft', es: '6.40 m' },
          beam:         { en: '8.5 ft', es: '2.33 m' },
          depth:        { en: '1.33 m', es: '1.33 m' },
          draft:        { en: '0.59 m', es: '0.59 m' },
          passengers:   { en: '11 pax', es: '11 pax' },
          fuelCapacity: { en: '60 GAL', es: '60 GAL' },
          maxLoad:      { en: '1400 kg', es: '1400 kg' },
          engines:      { en: '250 HP', es: '250 HP' },
        },
        features: {
          en: [
            'Command, control and monitoring system',
            'Steering compass / Manual binoculars',
            'Navigation lights / Marine spotlight',
            'GPS / Marine VHF radio / Marine UHF radio',
            'Speaker system / Electric horn',
            'Aluminum oars / Toolbox / Telescopic boat hook',
            'Three 12V batteries / Battery switch',
            'Two 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-pound ABC type fire extinguishers',
            '3" type D fender / Four 8" fenders',
            'SIX 10" cleats / Nylon rope',
            'Stainless steel swivel shackles',
            '22-pound aluminum anchor / Stainless steel chain',
            '26 life jackets / Two life rings',
            'Outboard motor guard / Bow Guard (Push kneel)',
          ],
          es: [
            'Sistema de comando, control y vigilancia',
            'Compás magnético / Binoculares marinos',
            'Luces de navegación / Reflector fijo',
            'GPS / Radio VHF marino / Radio UHF',
            'Altavoz con altoparlante / Pito eléctrico',
            'Remos en aluminio / Caja de herramientas / Bichero telescópico',
            'Tres baterías 12V / Switch de baterías',
            'Dos bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8"',
            'Seis cornamusas de trabajo de 10"',
            'Cable de nylon / Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '26 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
      {
        id: 'mt-31',
        name: 'MT-31',
        tagline: 'The Ultimate Day Cruiser',
        price: 'From $165,000',
        coverImage: IMAGES.mt31,
        images: [
          IMAGES.mt31Gallery1,
          IMAGES.mt31Gallery2,
          IMAGES.mt31Gallery3,
          IMAGES.mt31Gallery4,
          IMAGES.mt31Gallery5,
        ],
        pdfEs: '/docs/ficha-mt31-es.pdf',
        pdfEn: '/docs/ficha-mt31-en.pdf',
        specs: {
          loa:          { en: '31 ft', es: '9.50 m' },
          beam:         { en: '9.5 ft', es: '2.90 m' },
          depth:        { en: '1.60 m', es: '1.60 m' },
          draft:        { en: '0.59 m', es: '0.59 m' },
          passengers:   { en: '13 pax', es: '13 pax' },
          fuelCapacity: { en: '120 GAL', es: '120 GAL' },
          maxLoad:      { en: '3630 kg', es: '3630 kg' },
          engines:      { en: '2 x 250 HP', es: '2 x 250 HP' },
        },
        features: {
          en: [
            'Command, control and monitoring system',
            'Steering compass / Manual binoculars',
            'Navigation lights / Marine spotlight',
            'GPS / Marine VHF radio / Marine UHF radio',
            'Speaker system / Electric horn',
            'Aluminum oars / Toolbox / Telescopic boat hook',
            'Three 12V batteries / Battery switch / Electric cables',
            'Two 3700 GPH bilge pumps',
            'Waterproof rechargeable flashlight',
            'Two 20-pound ABC type fire extinguishers',
            '3" type D fender / Four 8" fenders',
            'SIX 10" cleats / Nylon rope',
            'Stainless steel swivel shackles',
            '22-pound aluminum anchor / Stainless steel chain',
            '26 life jackets / Two life rings',
            'Outboard motor guard / Bow Guard (Push kneel)',
          ],
          es: [
            'Sistema de comando, control y vigilancia',
            'Compás magnético / Binoculares marinos',
            'Luces de navegación / Reflector fijo',
            'GPS / Radio VHF marino / Radio UHF',
            'Altavoz con altoparlante / Pito eléctrico',
            'Remos en aluminio / Caja de herramientas / Bichero telescópico',
            'Tres baterías 12V / Switch de baterías / Cables eléctricos',
            'Dos bombas de achique de 3700 GPH',
            'Linterna recargable resistente al agua',
            'Dos extintores tipo ABC de 20 lb (cada uno)',
            'Defensa tipo D de 3" / Cuatro defensas de 8"',
            'Seis cornamusas de trabajo de 10"',
            'Cable de nylon / Grillete de acero inoxidable',
            'Ancla de aluminio de 22 libras / Cadena de acero inoxidable',
            '26 chalecos salvavidas / 02 aros salvavidas',
            'Defensa de motores fuera de borda / Protector de quilla (push kneel)',
          ],
        },
      },
    ],
  },

  // ── WORK ── 
 institutional: {
  category: 'Professional Series',
  models: [
    {
      id: 'pilot-42',
      name: 'Pilot 42',
      tagline: 'Professional Harbor Pilot Vessel',
     // price: 'Custom Quote',
      coverImage: IMAGES.pilot42,
      images: [
        IMAGES.pilot42Gallery1,
        IMAGES.pilot42Gallery2,
        IMAGES.pilot42Gallery3,
        IMAGES.pilot42Gallery4,
        IMAGES.pilot42Gallery5,
      ],
      pdfEs: '/docs/ficha-pilot42-es.pdf',
      pdfEn: '/docs/ficha-pilot42-en.pdf',
      specs: {
        loa:          { en: '42 ft', es: '12.80 m' },
        beam:         { en: '13 ft', es: '4.00 m' },
        crew:         { en: '4-6 crew', es: '4-6 tripulantes' },
        engines:      { en: 'Twin Diesel 600-800 HP', es: 'Doble Diésel 600-800 HP' },
        maxSpeed:     { en: '28 knots', es: '28 nudos' },
        range:        { en: '300 nm', es: '300 mn' },
      },
      features: {
        en: [
          'Heavy-duty commercial construction',
          'Shock-mitigating crew seats',
          'Advanced radar and navigation suite',
          'Professional grade VHF radio system',
          'Heated wheelhouse',
          'Bow thruster for precise maneuvering',
          'Commercial grade hull',
          'Professional navigation equipment',
          'Weather protection systems',
          'Easy boarding systems',
        ],
        es: [
          'Construcción comercial de alta resistencia',
          'Asientos de tripulación anti-impacto',
          'Sistema avanzado de radar y navegación',
          'Sistema de radio VHF grado profesional',
          'Cabina de mando climatizada',
          'Propulsor de proa para maniobras precisas',
          'Casco de grado comercial',
          'Equipos de navegación profesional',
          'Sistemas de protección climática',
          'Sistemas de embarque fácil',
        ],
      },
    },
    {
      id: 'pilot-38',
      name: 'Pilot 38',
      tagline: 'Compact Professional Vessel',
      price: 'Custom Quote',
      coverImage: IMAGES.pilot42Profile,
      images: [
        IMAGES.pilot38Gallery1,
        IMAGES.pilot38Gallery2,
        IMAGES.pilot38Gallery3,
      ],
      pdfEs: '/docs/ficha-pilot38-es.pdf',
      pdfEn: '/docs/ficha-pilot38-en.pdf',
      specs: {
        loa:          { en: '38 ft', es: '11.60 m' },
        beam:         { en: '12 ft', es: '3.70 m' },
        crew:         { en: '3-4 crew', es: '3-4 tripulantes' },
        engines:      { en: 'Twin Diesel 500-700 HP', es: 'Doble Diésel 500-700 HP' },
        maxSpeed:     { en: '30 knots', es: '30 nudos' },
        range:        { en: '250 nm', es: '250 mn' },
      },
      features: {
        en: [
          'Commercial grade hull',
          'Professional navigation equipment',
          'Ergonomic crew area',
          'VHF and communication systems',
          'Weather protection',
          'Easy boarding systems',
          'Shock-mitigating crew seats',
          'Advanced radar system',
          'Fuel-efficient diesel engines',
          'Reinforced structural frame',
        ],
        es: [
          'Casco de grado comercial',
          'Equipos de navegación profesional',
          'Área de tripulación ergonómica',
          'Sistemas VHF y comunicaciones',
          'Protección climática',
          'Sistemas de embarque fácil',
          'Asientos de tripulación anti-impacto',
          'Sistema avanzado de radar',
          'Motores diésel de bajo consumo',
          'Estructura reforzada',
        ],
      },
    },
  ],
},


  // ── MILITARY ──
  military: {
    category: 'Defense & Tactical Series',
    models: [
      {
        id: 'alligator',
        name: 'Alligator',
        tagline: 'Military Grade Tactical Patrol',
        price: 'Government Contract',
        coverImage: IMAGES.alligator,
        images: [
          IMAGES.alligatorGallery1,
          IMAGES.alligatorGallery2,
          IMAGES.alligatorGallery3,
        ],
        pdfEs: '/docs/ficha-alligator-es.pdf',
        pdfEn: '/docs/ficha-alligator-en.pdf',
        specs: {
          loa:      { en: '45 ft', es: '13.70 m' },
          beam:     { en: '14 ft', es: '4.30 m' },
          crew:     { en: '6-8 crew', es: '6-8 tripulantes' },
          engines:  { en: 'Twin Diesel 900-1200 HP', es: 'Doble Diesel 900-1200 HP' },
          maxSpeed: { en: '40 knots', es: '40 nudos' },
          range:    { en: '400 nm', es: '400 mn' },
        },
        features: {
          en: [
            'Ballistic protection systems',
            'Military-grade electronics suite',
            'Weapon mounting points',
            'Night vision compatible lighting',
            'Reinforced hull construction',
            'Tactical communications systems',
            'Shock-mitigating crew seats',
            'Advanced radar and sensor systems',
            'Secure encrypted communications',
            'Mission-configurable deck layout',
          ],
          es: [
            'Sistemas de proteccion balistica',
            'Suite electronica de grado militar',
            'Puntos de montaje de armamento',
            'Iluminacion compatible con vision nocturna',
            'Construccion de casco reforzado',
            'Sistemas de comunicaciones tacticas',
            'Asientos de tripulacion anti-impacto',
            'Sistemas avanzados de radar y sensores',
            'Comunicaciones seguras encriptadas',
            'Cubierta configurable para misiones',
          ],
        },
      },
      {
        id: 'tactical-45',
        name: 'Tactical 45',
        tagline: 'Multi-Mission Defense Platform',
        price: 'Government Contract',
        coverImage: IMAGES.alligatorAction,
        images: [
          IMAGES.tactical45Gallery1,
          IMAGES.tactical45Gallery2,
          IMAGES.tactical45Gallery3,
        ],
        pdfEs: '/docs/ficha-tactical45-es.pdf',
        pdfEn: '/docs/ficha-tactical45-en.pdf',
        specs: {
          loa:      { en: '45 ft', es: '13.70 m' },
          beam:     { en: '14.5 ft', es: '4.40 m' },
          crew:     { en: '8-10 crew', es: '8-10 tripulantes' },
          engines:  { en: 'Triple Diesel 1200-1500 HP', es: 'Triple Diesel 1200-1500 HP' },
          maxSpeed: { en: '45 knots', es: '45 nudos' },
          range:    { en: '450 nm', es: '450 mn' },
        },
        features: {
          en: [
            'Advanced ballistic protection',
            'Integrated weapon systems',
            'Tactical radar and sensors',
            'Secure communications',
            'Shock-mitigating seating',
            'Mission-configurable deck',
            'Night vision compatible systems',
            'Heavy-duty reinforced hull',
            'Multi-role operational capability',
            'Military-grade navigation suite',
          ],
          es: [
            'Proteccion balistica avanzada',
            'Sistemas de armamento integrados',
            'Radar tactivo y sensores',
            'Comunicaciones seguras',
            'Asientos anti-impacto',
            'Cubierta configurable para misiones',
            'Sistemas compatibles con vision nocturna',
            'Casco reforzado de alta resistencia',
            'Capacidad operacional multirol',
            'Suite de navegacion de grado militar',
          ],
        },
      },
    ],
  },
}; // <--- ¡AQUÍ ESTÁ LA LLAVE QUE FALTABA!

export const STORE_PRODUCTS = [
  { id: 1, name: 'Maritima Premium Polo', category: 'Apparel', price: 65, image: IMAGES.storeApparel },
  { id: 2, name: 'Marine Safety Kit', category: 'Gear & Accessories', price: 149, image: IMAGES.storeGear },
  { id: 3, name: 'GPS Chartplotter Pro', category: 'Electronics', price: 899, image: IMAGES.storeElectronics },
  { id: 4, name: 'Maritima Cap', category: 'Apparel', price: 35, image: IMAGES.storeApparel },
  { id: 5, name: 'Boat Fender Set', category: 'Gear & Accessories', price: 89, image: IMAGES.storeGear },
  { id: 6, name: 'Marine Radio VHF', category: 'Electronics', price: 349, image: IMAGES.storeElectronics },
];

export const NEWS_ARTICLES = [
  {
    id: 1,
    title: 'Maritima Boats Launches New MT-31 Model',
    excerpt: 'Our latest addition to the Lifestyle Series brings unprecedented luxury and performance to the recreational boating market.',
    date: '2026-02-15',
    category: 'Product Launch',
    image: IMAGES.mt31,
  },
  {
    id: 2,
    title: 'Pilot 42 Receives Industry Excellence Award',
    excerpt: 'The Professional Series Pilot 42 has been recognized for outstanding design and functionality in commercial vessel operations.',
    date: '2026-01-20',
    category: 'Awards',
    image: IMAGES.pilot42Profile,
  },
  {
    id: 3,
    title: 'Defense Contract: Alligator Series Expansion',
    excerpt: 'Maritima Boats secures major contract to deliver tactical vessels to international defense forces.',
    date: '2025-12-10',
    category: 'Business',
    image: IMAGES.alligatorAction,
  },
];
